### ISSUE TITLE
Start node index.js is failed

### ISSUE THREAD

**Issue by Infiell** [DogeNetwork/v4#128]
Log file 2024-11-06T11_58_55_613Z-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle surfdoge@4.4.13~prestart: surfdoge@4.4.13
6 info lifecycle surfdoge@4.4.13~start: surfdoge@4.4.13
7 verbose lifecycle surfdoge@4.4.13~start: unsafe-perm in lifecycle true
8 verbose lifecycle surfdoge@4.4.13~start: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/v4/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle surfdoge@4.4.13~start: CWD: /root/v4
10 silly lifecycle surfdoge@4.4.13~start: Args: [ '-c', 'node index.js' ]
11 silly lifecycle surfdoge@4.4.13~start: Returned: code: 1  signal: null
12 info lifecycle surfdoge@4.4.13~start: Failed to exec start script
13 verbose stack Error: surfdoge@4.4.13 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid surfdoge@4.4.13
15 verbose cwd /root/v4
16 verbose Linux 5.4.0-200-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error surfdoge@4.4.13 start: `node index.js`
22 error Exit status 1
23 error Failed at the surfdoge@4.4.13 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by Infiell** [comment]
```
root@v62372:~/v4# npm start

> surfdoge@4.4.13 start /root/v4
> node index.js

/root/v4/index.js:1
import express from 'express';
       ^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! surfdoge@4.4.13 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the surfdoge@4.4.13 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /www/server/nodejs/v16.9.0/cache/_logs/2024-11-06T11_58_55_613Z-debug.log
```

**Comment by silentsparrows** [comment]
Seems that your Node.js is outdated. You need v20 or above to run this application.
https://stackoverflow.com/questions/8191459/how-do-i-update-node-js
